# Generated by Django 6.0.4 on 2026-04-28 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetails',
            name='offer',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetails'),
        ),
    ]
