# Generated by Django 6.0.4 on 2026-04-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_remove_offerdetails_offer_offermodel_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='details',
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers_app.offermodel'),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='offert_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='revisions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
