# Generated by Django 6.0.4 on 2026-04-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offermodel_details_offerdetails_offer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetails',
            old_name='offert_type',
            new_name='offer_type',
        ),
    ]
