# Generated by Django 6.0.4 on 2026-04-30 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers_app', '0005_offerdetails_created_at_offerdetails_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('revisions', models.IntegerField(default=0)),
                ('delivery_time_in_days', models.IntegerField()),
                ('price', models.IntegerField()),
                ('features', models.JSONField(default=list)),
                ('offer_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buisness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('offer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetails')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
