# Generated by Django 6.0.4 on 2026-05-02 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_app', '0002_alter_ordermodel_buisness_user_and_more'),
        ('offers_app', '0005_offerdetails_created_at_offerdetails_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='buisness_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_time_in_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetails'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
